export const surpriseMePrompts = [
  'a magical forest where the trees have glowing fruits, digital art',
  'a hyper-realistic portrait of a lion wearing a suit and tie, sitting at a desk',
  'a steampunk airship flying through a canyon filled with bioluminescent plants',
  'an underwater city made entirely of glass, lit by glowing sea creatures',
  'a 3D render of a futuristic motorcycle designed like a hummingbird, in neon colors',
  'a panda bear dressed as a cowboy, riding a unicorn through the desert',
  'a watercolor painting of a cozy library built inside a giant tree, with small creatures reading books',
  'a cyberpunk samurai wielding a neon sword in a futuristic Tokyo alley',
  'a picnic on the surface of the moon with a view of Earth in the background, digital art',
  'a mosaic-style artwork of a phoenix rising from flames',
  'a fantasy dragon made entirely of ice, perched on a glowing crystal mountain',
  'a whimsical tea party attended by forest animals, set in a magical glade',
  'a futuristic city where buildings float in the sky, with bridges made of light',
  'an abstract oil painting of the ocean with waves that look like musical notes',
  'a robot chef preparing a gourmet meal in a sleek futuristic kitchen',
  'a high-fashion photoshoot featuring aliens wearing avant-garde outfits',
  'a surreal desert landscape with floating rocks and an oversized hourglass',
  'a coffee shop run by cats, with tiny tables and cat-sized pastries, digital art',
  'an ancient temple hidden in a jungle, glowing with mysterious runes',
  'a medieval knight battling a giant octopus on a stormy sea, oil painting',
  'a futuristic train speeding through a landscape of glowing crystals, digital art',
  'a ballerina dancing on a floating platform above a city of clouds, vaporwave',
  'a portrait of a wolf wearing round glasses and a scarf, reading a book',
  'a giant jellyfish floating above a city skyline at sunset',
  'a mechanical bird taking flight in a clockwork-inspired sky, steampunk style',
  'a candyland-inspired city with buildings made of gingerbread and lollipops',
  'a glowing koi fish swimming in a night sky filled with stars, digital art',
  'a Viking ship sailing through a river of lava under a blood-red sky',
  'a paper origami dragon brought to life, flying over a serene lake',
  'a neon-lit diner in the middle of a snowy wasteland, digital art',
  'a futuristic skyscraper shaped like a tree, covered in greenery',
  'a kaleidoscopic fractal design of a galaxy, digital art',
  'a scene of ancient ruins being reclaimed by glowing alien vegetation',
  'a portrait of a fox wearing a monocle and sipping tea by a fireplace',
  'a fantasy kingdom carved into a mountainside, illuminated by a golden sunset',
  'a biomechanical jellyfish floating in the depths of the ocean, luminescent',
  'a whimsical scene of a hot air balloon shaped like a teapot, flying over a fantasy world',
  'a surreal painting of a clock melting into a waterfall, inspired by Dalí',
  'a futuristic astronaut holding a glowing crystal, standing on a barren alien planet',
  'a treehouse village built into a glowing mushroom forest, digital art',
  'a giant turtle carrying a miniature city on its back, sailing through an ocean of stars',
  'an abstract painting of a thunderstorm where the lightning bolts are rainbow-colored',
  'a samurai duel taking place in a field of glowing cherry blossoms at night',
  'a mythical creature that’s half-wolf, half-dragon, guarding a treasure hoard, digital art',
  'a robot playing a violin in a serene meadow with colorful butterflies around',
  'a group of penguins having a disco party under the Northern Lights',
  'a mystical portal in a desert, swirling with vibrant cosmic colors',
  'a futuristic cityscape with flying cars and holographic billboards, seen at sunset',
  'an enchanted castle floating above a serene lake with glowing lotus flowers',
]
